Neos:
  Flow:
    mvc:
      routes:
        # The following lines register the Flow default routes
        # For productive use you should move this setting to the main package of this
        # application and/or create custom routes.
        'Neos.Flow': true
